/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['action.js']) {
  _$jscoverage['action.js'] = [];
}
_$jscoverage['action.js'].source = [];
