/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['groupPool.js']) {
  _$jscoverage['groupPool.js'] = [];
  _$jscoverage['groupPool.js'][1] = 0;
  _$jscoverage['groupPool.js'][3] = 0;
  _$jscoverage['groupPool.js'][5] = 0;
  _$jscoverage['groupPool.js'][6] = 0;
  _$jscoverage['groupPool.js'][7] = 0;
  _$jscoverage['groupPool.js'][9] = 0;
  _$jscoverage['groupPool.js'][11] = 0;
  _$jscoverage['groupPool.js'][12] = 0;
  _$jscoverage['groupPool.js'][16] = 0;
  _$jscoverage['groupPool.js'][20] = 0;
}
_$jscoverage['groupPool.js'][1]++;
var sys = require("sys");
_$jscoverage['groupPool.js'][3]++;
var Group = require("./group");
_$jscoverage['groupPool.js'][5]++;
module.exports = (function () {
  _$jscoverage['groupPool.js'][6]++;
  var users = [];
  _$jscoverage['groupPool.js'][7]++;
  var fakeGlobalGroup = Group();
  _$jscoverage['groupPool.js'][9]++;
  return ({addUser: (function (user) {
  _$jscoverage['groupPool.js'][11]++;
  sys.puts("add user: " + user);
  _$jscoverage['groupPool.js'][12]++;
  fakeGlobalGroup.addUser(user);
}), groupForUser: (function (user) {
  _$jscoverage['groupPool.js'][16]++;
  return fakeGlobalGroup;
}), clear: (function () {
  _$jscoverage['groupPool.js'][20]++;
  fakeGlobalGroup = Group();
})});
});
_$jscoverage['groupPool.js'].source = ["var sys = require(\"sys\");","","var Group = require(\"./group\");","","module.exports = function() {","  var users = [];","  var fakeGlobalGroup = Group();","","  return {","    addUser: function(user) {","      sys.puts(\"add user: \" + user);","      fakeGlobalGroup.addUser(user);","    },","    ","    groupForUser: function(user) {","      return fakeGlobalGroup;","    },","    ","    clear: function() {","      fakeGlobalGroup = Group();","    }","  }","};"];
