source "http://rubygems.org"

#gem "eventmachine", "0.12.11", :git => "git://github.com/eventmachine/eventmachine.git"
gem "eventmachine"
gem "sinatra"
gem "async_sinatra", "0.2.3"
gem 'async-rack'
gem 'rack-test'
gem 'ruby-debug19'
gem "thin"
gem 'uuid'
gem 'bson_ext'
gem 'em-mongo'
