source "http://rubygems.org"

gem "eventmachine"
gem "sinatra"
gem "sinatra-reloader"
gem "async_sinatra", "0.5"
gem 'async-rack'
gem 'rack-test'
gem 'ruby-debug19'
gem "thin", '>= 1.2.11'
gem 'uuid'
gem 'bson_ext', '>= 1.1'
gem 'em-mongo', '>= 0.2.13'
gem 'mongo'
gem 'hoccer-api'
