require 'rake'
require 'rake/testtask'
require 'mongo'

namespace :test do

  Rake::TestTask.new(:functional) do |t|
    t.libs << "test"
    t.test_files = FileList['test/functional/*_test.rb']

    t.verbose = true
  end

  Rake::TestTask.new(:integration) do |t|
    t.libs << "test"
    t.test_files = FileList['test/integration/*_test.rb']

    t.verbose = true
  end

end

namespace :db do
  desc "Setup Database Indices"
  task :setup_indices do
    valid_environments = %w( production experimental testing development )

    unless valid_environments.include?( ENV['RACK_ENV'] )
      raise(
        ArgumentError,
        "RACK_ENV was not specified or invalid"
      )
    end

    env_indices = {
      "gps"         => "2d",
      "wifi.bssids" => 1,
      "mdns.own_id" => 1,
      "mdns.seen_ids" => 1,
      "channel.name" => 1,
      "client_uuid" => 1,
      "group_id"    => 1,
      "created_at"  => 1
    }

    lookup_indices = {
      "uuid" => 1,
      "hash" => 1
    }

    @conn = Mongo::Connection.new
    @db   = @conn["hoccer_#{ENV['RACK_ENV']}"]

    @coll = @db['environments']
    env_indices.each do |index|
      @coll.ensure_index( [index.to_a] )
    end

    @coll = @db['hoccer_lookups']
    lookup_indices.each do |index|
      @coll.ensure_index( [index.to_a] )
    end

  end
end
