require 'rake'
require 'rake/testtask'

namespace :test do

Rake::TestTask.new(:functional) do |t|
  t.libs << "test"
  t.test_files = FileList['test/functional/*_test.rb']

  t.verbose = true
end

Rake::TestTask.new(:integration) do |t|
  t.libs << "test"
  t.test_files = FileList['test/integration/*_test.rb']

  t.verbose = true
end

Rake::TestTask.new(:unit) do |t|
  t.libs << "test"
  t.test_files = FileList['test/test_*.rb']

  t.verbose = true
end

end
