/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['group.js']) {
  _$jscoverage['group.js'] = [];
  _$jscoverage['group.js'][1] = 0;
  _$jscoverage['group.js'][3] = 0;
  _$jscoverage['group.js'][4] = 0;
  _$jscoverage['group.js'][5] = 0;
  _$jscoverage['group.js'][7] = 0;
  _$jscoverage['group.js'][8] = 0;
  _$jscoverage['group.js'][9] = 0;
  _$jscoverage['group.js'][10] = 0;
  _$jscoverage['group.js'][14] = 0;
  _$jscoverage['group.js'][15] = 0;
  _$jscoverage['group.js'][16] = 0;
  _$jscoverage['group.js'][18] = 0;
  _$jscoverage['group.js'][19] = 0;
  _$jscoverage['group.js'][23] = 0;
  _$jscoverage['group.js'][24] = 0;
  _$jscoverage['group.js'][25] = 0;
  _$jscoverage['group.js'][26] = 0;
  _$jscoverage['group.js'][29] = 0;
  _$jscoverage['group.js'][30] = 0;
  _$jscoverage['group.js'][31] = 0;
  _$jscoverage['group.js'][35] = 0;
  _$jscoverage['group.js'][41] = 0;
  _$jscoverage['group.js'][45] = 0;
  _$jscoverage['group.js'][46] = 0;
  _$jscoverage['group.js'][47] = 0;
  _$jscoverage['group.js'][49] = 0;
  _$jscoverage['group.js'][53] = 0;
  _$jscoverage['group.js'][54] = 0;
  _$jscoverage['group.js'][55] = 0;
  _$jscoverage['group.js'][57] = 0;
}
_$jscoverage['group.js'][1]++;
var sys = require("sys");
_$jscoverage['group.js'][3]++;
module.exports = (function () {
  _$jscoverage['group.js'][4]++;
  var sender = {}, receiver = {};
  _$jscoverage['group.js'][5]++;
  var users = [];
  _$jscoverage['group.js'][7]++;
  var error = (function (mode) {
  _$jscoverage['group.js'][8]++;
  var actions = (sender[mode] || []).concat(receiver[mode] || []);
  _$jscoverage['group.js'][9]++;
  for (var key in actions) {
    _$jscoverage['group.js'][10]++;
    actions[key].error();
}
});
  _$jscoverage['group.js'][14]++;
  var deliverContent = (function (mode) {
  _$jscoverage['group.js'][15]++;
  var s = sender[mode][0];
  _$jscoverage['group.js'][16]++;
  s.success();
  _$jscoverage['group.js'][18]++;
  for (var key in receiver[mode]) {
    _$jscoverage['group.js'][19]++;
    receiver[mode][key].success(s.payload);
}
});
  _$jscoverage['group.js'][23]++;
  var verify = (function (mode, group) {
  _$jscoverage['group.js'][24]++;
  if (users.length <= 1) {
    _$jscoverage['group.js'][25]++;
    error(mode);
    _$jscoverage['group.js'][26]++;
    return;
  }
  _$jscoverage['group.js'][29]++;
  if ((sender[mode] || []).length == 1 && (receiver[mode] || []).length > 0) {
    _$jscoverage['group.js'][30]++;
    deliverContent(mode);
    _$jscoverage['group.js'][31]++;
    return;
  }
});
  _$jscoverage['group.js'][35]++;
  return ({users: users, sender: sender, receiver: receiver, addUser: (function (user) {
  _$jscoverage['group.js'][41]++;
  users.push(user);
}), send: (function (action) {
  _$jscoverage['group.js'][45]++;
  var senderForMode = sender[action.mode] || [];
  _$jscoverage['group.js'][46]++;
  senderForMode.push(action);
  _$jscoverage['group.js'][47]++;
  sender[action.mode] = senderForMode;
  _$jscoverage['group.js'][49]++;
  verify(action.mode, this);
}), receive: (function (action) {
  _$jscoverage['group.js'][53]++;
  var receiverForMode = receiver[action.mode] || [];
  _$jscoverage['group.js'][54]++;
  receiverForMode.push(action);
  _$jscoverage['group.js'][55]++;
  receiver[action.mode] = receiverForMode;
  _$jscoverage['group.js'][57]++;
  verify(action.mode, this);
})});
});
_$jscoverage['group.js'].source = ["var sys = require(\"sys\");","","module.exports =  function() {","  var sender = {}, receiver = {};","  var users = [];  ","     ","  var error = function(mode) {","    var actions = (sender[mode] || []).concat(receiver[mode] || []);","    for (var key in actions) {","      actions[key].error();","    }","  }        ","  ","  var deliverContent = function(mode) {","    var s = sender[mode][0];","    s.success();","    ","    for (var key in receiver[mode]) {","      receiver[mode][key].success(s.payload);","    }","  }","  ","  var verify = function(mode, group) {","    if (users.length &lt;= 1) {","      error(mode);","      return;","    }","    ","    if ((sender[mode] || []).length == 1 &amp;&amp; (receiver[mode] || []).length &gt; 0) {","      deliverContent(mode);","      return;","    }","  }","  ","  return {","    users: users,","    sender: sender,","    receiver: receiver,","  ","    addUser: function(user) {","      users.push(user);","    },","    ","    send: function(action) {","      var senderForMode = sender[action.mode] || [];","      senderForMode.push(action);","      sender[action.mode] = senderForMode;","","      verify(action.mode, this);","    },","    ","    receive: function(action) {","      var receiverForMode = receiver[action.mode] || [];","      receiverForMode.push(action);","      receiver[action.mode] = receiverForMode;","      ","      verify(action.mode, this);","    }    ","  }              ","};"];
